# Generated by Django 3.1.5 on 2021-01-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0002_upis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upis',
            new_name='Enroll',
        ),
        migrations.RenameModel(
            old_name='Predmet',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='predmet_id',
            new_name='predmet',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='student_id',
            new_name='student',
        ),
    ]
