# Generated by Django 3.1.5 on 2021-01-23 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0003_auto_20210123_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='predmet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='college_app.subject'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
